// <auto-generated />
using Discount.gRPC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.gRPC.Migrations
{
    [DbContext(typeof(DiscountContext))]
    partial class DiscountContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Discount.gRPC.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Percent")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkuId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "IPhone X 256GB",
                            Percent = 15,
                            SkuId = "abc123"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Laptop ASUS Travel Mate RAM 32GB",
                            Percent = 20,
                            SkuId = "mnp456"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Samsung Galaxy 256GB",
                            Percent = 15,
                            SkuId = "xyz789"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
