// <auto-generated />
using System;
using Discount.gRPC.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Discount.gRPC.Migrations
{
    [DbContext(typeof(DiscountContext))]
    partial class DiscountContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Discount.gRPC.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Percent")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coupons");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "IPhone X 256GB",
                            Percent = 15,
                            ProductId = new Guid("6267e3aa-3e20-4600-8cf8-ae908a55eb30")
                        },
                        new
                        {
                            Id = 2,
                            Description = "Laptop ASUS Travel Mate RAM 32GB",
                            Percent = 20,
                            ProductId = new Guid("5853fe3d-677c-4bce-aa27-d12bf2b45e2e")
                        },
                        new
                        {
                            Id = 3,
                            Description = "Samsung Galaxy 256GB",
                            Percent = 15,
                            ProductId = new Guid("6267e3aa-3e20-4600-8cf8-ae908a55eb30")
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
