version: '3.4'

services:
  songservicedb:
    container_name: songservicedb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1612003
      - POSTGRES_DB=SongServiceDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_songservice:/var/lib/postgresql/data/
  songservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Marten=Host=songservicedb;Port=5432;Database=SongServiceDb;UserId=postgres;Password=1612003;Include Error Detail=true
    depends_on:
      - songservicedb
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
